### ISSUE TITLE
Cannot run inference on given datasets

### ISSUE THREAD

**Issue by JahedulAnowar** [Zhaozixiang1228/GDSR-DCTNet#9]
Thank you for sharing the code.

I am trying to test inference.
However, when I execute the `processing_testsets.py` I get `FileNotFoundError` :

```
$ python3 processing_testsets.py 
Traceback (most recent call last):
  File "processing_testsets.py", line 20, in <module>
    processing_testsets_synthetic(scale,data_path,save_path,dataset_name)
  File "/home/user/depth/GDSR-DCTNet/dataset_processing/Processing_testsets_synthetic.py", line 94, in processing_testsets_synthetic
    filename+'-depthHr.npy'), depth_hr[None, :, :].astype(np.float32))
  File "<__array_function__ internals>", line 6, in save
  File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'DatasetsAfterProcessing/Middlebury_AfterProcessing_4X/DepthHR/RawDatasets/Middlebury/Depth/Middlebury_01_output_depth-depthHr.npy'
```

**Comment by Zhaozixiang1228** [comment]
Hi, Your path is wrong. The correct path should be: DatasetsAfterProcessing/Middlebury_AfterProcessing_4X/DepthHR/Middlebury_01_output_depth-depthHr.npy
